<?php
/**
 * User: Alexander.Arutyunov
 * Date: 09.07.13
 * Time: 13:40
 */

namespace My\Db;


class PdoStatement extends \PDOStatement
{
    protected $conn;

    protected function __construct(\PDO $conn)
    {
        $this->conn = $conn;
    }

    /*public function fetch($fetch_style = null, $cursor_orientation = \PDO::FETCH_ORI_NEXT, $cursor_offset = 0)
    {
        dump(__METHOD__, func_get_args());
//        if ($this->getAttribute(\PDO::FETCH_CLASSTYPE))
//        dump($this->getAttribute(\PDO::FETCH_CLASSTYPE));
        return parent::fetch($fetch_style, $cursor_orientation, $cursor_offset);
    }

    public function setAttribute($attribute, $value)
    {
        dump(__METHOD__, func_get_args());
        parent::setAttribute($attribute, $value); // TODO: Change the autogenerated stub
    }


    public function setFetchMode($mode, $params = NULL)
    {
        dump(__METHOD__);
        parent::setFetchMode($mode); // TODO: Change the autogenerated stub
    }*/
}